export const UPDATE_LOADING = 'UPDATE_LOADING'
export const UPDATE_DIRECTION = 'UPDATE_DIRECTION'

export const GET_AUTHORIZE = 'GET_AUTHORIZE'

export const SHOW_MSG = 'SHOW_MSG'
export const HIDE_MSG = 'HIDE_MSG'